spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5439/sample_container
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8088


